"use client";
import {useEffect,useMemo,useState} from "react";
type A={id:string;created_at:string;full_name:string;phone:string;email:string|null;preferred_date:string;preferred_time:string;service:string;message:string|null;status:"PENDING"|"CONFIRMED"|"CANCELLED";admin_note:string|null};
export default function Admin(){const [items,setItems]=useState<A[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState("ALL"),[q,setQ]=useState("");
async function load(){setLoading(true);try{const r=await fetch("/api/admin");if(r.status===401){location.href="/admin/login";return}const x=await r.json();if(!r.ok)throw new Error();setItems(x.appointments)}catch{setError("Unable to load appointments.")}finally{setLoading(false)}}useEffect(()=>{load()},[]);
const shown=useMemo(()=>items.filter(a=>(filter==="ALL"||a.status===filter)&&`${a.full_name} ${a.phone} ${a.email||""}`.toLowerCase().includes(q.toLowerCase())),[items,filter,q]);
async function update(id:string,status:string,admin_note?:string){const r=await fetch("/api/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,admin_note})});if(r.ok)load()}
async function logout(){await fetch("/api/admin/logout",{method:"POST"});location.href="/admin/login"}
const counts={ALL:items.length,PENDING:items.filter(x=>x.status==="PENDING").length,CONFIRMED:items.filter(x=>x.status==="CONFIRMED").length,CANCELLED:items.filter(x=>x.status==="CANCELLED").length};
return <section className="section pt-10"><div className="container"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">ADMIN</div><h1 className="h2 mt-3">Appointment requests</h1></div><button onClick={logout} className="btn btn-secondary">Sign out</button></div><div className="mt-9 grid gap-3 sm:grid-cols-4">{(["ALL","PENDING","CONFIRMED","CANCELLED"] as const).map(s=><button key={s} onClick={()=>setFilter(s)} className={`card p-5 text-left ${filter===s?"ring-2 ring-[#2EC4B6]":""}`}><div className="text-xs font-bold text-[#536568]">{s}</div><div className="mt-2 text-3xl font-semibold">{counts[s]}</div></button>)}</div><div className="mt-7 flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, phone or email" className="w-full max-w-md rounded-xl border border-[#d9e6e4] bg-white px-4 py-3"/><button onClick={load} className="btn btn-secondary">Refresh</button></div>{error&&<p className="mt-5 text-red-700">{error}</p>}{loading?<div className="card mt-6 p-8">Loading appointments…</div>:shown.length===0?<div className="card mt-6 p-10 text-center text-[#536568]">No appointments match this view.</div>:<div className="mt-6 grid gap-4">{shown.map(a=><article key={a.id} className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{a.full_name}</h2><p className="mt-1 text-sm text-[#536568]">{a.phone}{a.email?` · ${a.email}`:""}</p></div><span className="rounded-lg border px-3 py-1 text-xs font-bold">{a.status}</span></div><div className="mt-5 grid gap-4 text-sm md:grid-cols-4"><div><b>Service</b><p className="mt-1 text-[#536568]">{a.service}</p></div><div><b>Date</b><p className="mt-1 text-[#536568]">{a.preferred_date}</p></div><div><b>Time</b><p className="mt-1 text-[#536568]">{a.preferred_time}</p></div><div><b>Created</b><p className="mt-1 text-[#536568]">{new Date(a.created_at).toLocaleString()}</p></div></div>{a.message&&<p className="mt-5 rounded-xl bg-[#F8FBFA] p-4 text-sm leading-7"><b>Message:</b> {a.message}</p>}<div className="mt-5 flex flex-wrap gap-2"><button disabled={a.status==="CONFIRMED"} onClick={()=>{if(confirm("Confirm this appointment?"))update(a.id,"CONFIRMED",a.admin_note||"")}} className="btn btn-teal text-sm disabled:opacity-40">Confirm</button><button disabled={a.status==="CANCELLED"} onClick={()=>{if(confirm("Cancel this appointment?"))update(a.id,"CANCELLED",a.admin_note||"")}} className="btn btn-secondary text-sm disabled:opacity-40">Cancel</button><AdminNote initial={a.admin_note||""} onSave={v=>update(a.id,a.status,v)}/></div></article>)}</div>}</div></section>}
function AdminNote({initial,onSave}:{initial:string;onSave:(v:string)=>void}){const [v,setV]=useState(initial);return <div className="flex min-w-[240px] flex-1 gap-2"><input value={v} onChange={e=>setV(e.target.value)} placeholder="Admin note" maxLength={1000} className="min-w-0 flex-1 rounded-xl border border-[#d9e6e4] px-3 py-2 text-sm"/><button onClick={()=>onSave(v)} className="btn btn-secondary text-sm">Save note</button></div>}
