export const services=[
 {slug:"smile-design",title:"Smile Design",ar:"تصميم الابتسامة",desc:"Thoughtful aesthetic planning for a smile that feels natural to you.",arDesc:"تخطيط جمالي مدروس لابتسامة طبيعية تشبهك."},
 {slug:"orthodontics",title:"Orthodontics",ar:"تقويم الأسنان",desc:"Treatment planning focused on alignment, function, and a confident smile.",arDesc:"تخطيط يركز على ترتيب الأسنان ووظيفتها وابتسامة أكثر ثقة."},
 {slug:"restorative-dentistry",title:"Restorative Dentistry",ar:"علاج الأسنان الترميمي",desc:"Restoring damaged or missing tooth structure with a focus on function and appearance.",arDesc:"استعادة الأجزاء المتضررة أو المفقودة من الأسنان مع الاهتمام بالوظيفة والمظهر."},
 {slug:"preventive-care",title:"Preventive Care",ar:"العناية الوقائية",desc:"Regular care and guidance to help you maintain a healthy smile.",arDesc:"رعاية وإرشادات منتظمة تساعدك في الحفاظ على ابتسامة صحية."}
];
export const serviceDetails:Record<string,{title:string;ar:string;hero:string;arHero:string;body:string;arBody:string;sections:string[];arSections:string[]}>={
 "smile-design":{title:"Smile Design",ar:"تصميم الابتسامة",hero:"Your smile should still look like you.",arHero:"ابتسامتك تفضل شبهك.",body:"Smile design is not about copying a template. It is about understanding proportions, preferences, facial harmony, and the clinical factors that shape a suitable treatment plan.",arBody:"تصميم الابتسامة مش معناه نسخ شكل جاهز؛ هو فهم للتناسق والتفضيلات وانسجام ملامح الوجه والعوامل الطبية التي تساعد في وضع خطة مناسبة.",sections:["What we consider","Your goals","Clinical assessment","Treatment planning","Follow-up"],arSections:["ما نضعه في الاعتبار","أهدافك","التقييم الطبي","خطة العلاج","المتابعة"]},
 "orthodontics":{title:"Orthodontics",ar:"تقويم الأسنان",hero:"A more considered approach to alignment.",arHero:"نهج مدروس أكثر لترتيب الأسنان.",body:"Orthodontic treatment is planned around the individual's teeth, bite, goals, and clinical needs. The right option can only be determined after assessment.",arBody:"يتم تخطيط تقويم الأسنان وفق حالة الأسنان والعضة والأهداف والاحتياجات الطبية لكل شخص. الخيار المناسب يتحدد بعد التقييم.",sections:["Initial assessment","Treatment options","Progress and follow-up","Retention / aftercare"],arSections:["التقييم الأولي","خيارات العلاج","التقدم والمتابعة","التثبيت والعناية بعد العلاج"]},
 "restorative-dentistry":{title:"Restorative Dentistry",ar:"علاج الأسنان الترميمي",hero:"Restore function. Preserve confidence.",arHero:"استعيدي الوظيفة وحافظي على ثقتك.",body:"Restorative dentistry focuses on addressing damaged or missing tooth structure while keeping function and appearance in view.",arBody:"يركز العلاج الترميمي على التعامل مع الأجزاء المتضررة أو المفقودة من الأسنان مع مراعاة الوظيفة والمظهر.",sections:["Assessment","Treatment planning","Restoration","Follow-up care"],arSections:["التقييم","خطة العلاج","الترميم","المتابعة"]},
 "preventive-care":{title:"Preventive Care",ar:"العناية الوقائية",hero:"Small habits. Long-term care.",arHero:"عادات بسيطة. عناية على المدى الطويل.",body:"Preventive dentistry focuses on regular monitoring, professional care when needed, and simple habits that support oral health.",arBody:"تركز العناية الوقائية على المتابعة المنتظمة والرعاية المهنية عند الحاجة والعادات البسيطة التي تدعم صحة الفم.",sections:["Regular monitoring","Professional care when appropriate","Practical guidance","Long-term follow-up"],arSections:["المتابعة المنتظمة","الرعاية المهنية عند الحاجة","إرشادات عملية","المتابعة طويلة المدى"]}
};
export const nav=[["/","Home","الرئيسية"],["/services","Services","الخدمات"],["/about","About","عن العيادة"],["/technology","Technology","التكنولوجيا"],["/faq","FAQ","الأسئلة الشائعة"],["/contact","Contact","تواصل معنا"]];
export const phone="01552708582", email="dr.nada2005@gmail.com";
