"use client";
import {useState} from "react"; import {services,phone,email} from "@/lib/content"; import {appointmentSchema} from "@/lib/validation";
export default function Book(){const [state,setState]=useState<"idle"|"loading"|"success"|"error">("idle");const [errors,setErrors]=useState<Record<string,string>>({});
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setErrors({});const fd=new FormData(e.currentTarget);const data=Object.fromEntries(fd.entries());data.consent=fd.get("consent")=== "on";const p=appointmentSchema.safeParse(data);if(!p.success){const x:Record<string,string>={};p.error.issues.forEach(i=>x[String(i.path[0])]=i.message);setErrors(x);return}setState("loading");try{const r=await fetch("/api/appointments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p.data)});if(!r.ok)throw new Error();setState("success");e.currentTarget.reset()}catch{setState("error")}}
return <section className="section"><div className="container grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="eyebrow">APPOINTMENTS</div><h1 className="display mt-5">Request an appointment.</h1><p className="body mt-6">Choose a preferred date and time and tell us what you would like help with. Your request will be sent to the clinic for review.</p><div className="mt-7 rounded-2xl bg-[#DDF3EF] p-5 text-sm leading-7 text-[#12343B]"><b>This is an appointment request, not an instant confirmation.</b><br/>The clinic will confirm the appointment after reviewing availability.</div><div className="mt-8 text-sm text-[#536568]">Prefer to contact us? <a className="font-semibold text-[#176B87]" href={`tel:+201552708582`}>{phone}</a> · <a className="font-semibold text-[#176B87]" href={`mailto:${email}`}>{email}</a></div></div>
<div className="card p-6 md:p-9">{state==="success"?<div className="py-14 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#DDF3EF] text-2xl text-[#176B87]">✓</div><h2 className="mt-6 text-2xl font-semibold">Request received.</h2><p className="mx-auto mt-4 max-w-lg leading-8 text-[#536568]">Your appointment request has been received. The clinic will review your request and contact you to confirm the appointment.</p><button className="btn btn-secondary mt-8" onClick={()=>setState("idle")}>Send another request</button></div>:<form onSubmit={submit} noValidate className="grid gap-5">
<Field label="Full name" name="full_name" error={errors.full_name}/><Field label="Phone number" name="phone" type="tel" error={errors.phone}/><Field label="Email (optional)" name="email" type="email" error={errors.email}/>
<div className="grid gap-5 md:grid-cols-2"><Field label="Preferred date" name="preferred_date" type="date" error={errors.preferred_date}/><Field label="Preferred time" name="preferred_time" type="time" error={errors.preferred_time}/></div>
<div><label className="mb-2 block text-sm font-semibold" htmlFor="service">Service</label><select id="service" name="service" className="w-full rounded-xl border border-[#d9e6e4] bg-white px-4 py-3" defaultValue=""><option value="" disabled>Select a service</option>{[...services].map(s=><option key={s}>{s}</option>)}</select>{errors.service&&<p className="mt-1 text-sm text-red-700">{errors.service}</p>}</div>
<div><label className="mb-2 block text-sm font-semibold" htmlFor="message">Message / notes <span className="font-normal text-[#536568]">(optional)</span></label><textarea id="message" name="message" rows={4} className="w-full resize-y rounded-xl border border-[#d9e6e4] bg-white px-4 py-3"/>{errors.message&&<p className="mt-1 text-sm text-red-700">{errors.message}</p>}</div>
<label className="flex gap-3 text-sm leading-6 text-[#536568]"><input type="checkbox" name="consent" className="mt-1 h-4 w-4 shrink-0"/><span>I agree to have Nada Smile use the information above to review my appointment request. Please do not include detailed medical history.</span></label>{errors.consent&&<p className="-mt-3 text-sm text-red-700">{errors.consent}</p>}
{state==="error"&&<div role="alert" className="rounded-xl bg-[#fff3f2] p-4 text-sm text-red-800">We couldn't submit your request right now. Please try again or contact the clinic directly.</div>}
<button disabled={state==="loading"} className="btn btn-primary w-full py-4 disabled:opacity-60">{state==="loading"?"Submitting…":"Submit appointment request"}</button>
</form>}</div></div></section>}
function Field({label,name,type="text",error}:{label:string;name:string;type?:string;error?:string}){return <div><label className="mb-2 block text-sm font-semibold" htmlFor={name}>{label}</label><input id={name} name={name} type={type} className="w-full rounded-xl border border-[#d9e6e4] bg-white px-4 py-3" />{error&&<p className="mt-1 text-sm text-red-700">{error}</p>}</div>}
