"use client";
import Image from "next/image"; import Link from "next/link"; import {useEffect,useState} from "react"; import {nav} from "@/lib/content";
export default function Shell({children}:{children:React.ReactNode}){
 const [ar,setAr]=useState(false),[open,setOpen]=useState(false);
 useEffect(()=>{setAr(localStorage.getItem("ns-lang")==="ar")},[]);
 useEffect(()=>{document.documentElement.lang=ar?"ar":"en";document.documentElement.dir=ar?"rtl":"ltr";localStorage.setItem("ns-lang",ar?"ar":"en")},[ar]);
 return <div className={ar?"rtl":""}><header className="sticky top-0 z-50 border-b border-[#dfeae8] bg-[#f8fbfaf0] backdrop-blur-md"><div className="container flex h-[72px] items-center justify-between gap-5">
  <Link href="/"><Image src="/brand/assets/logo-primary.png" alt="Nada Smile Dental Clinic" width={154} height={54} priority className="h-11 w-auto"/></Link>
  <nav className="hidden lg:flex items-center gap-6 text-sm font-semibold">{nav.map(([href,en,ara])=><Link key={href} href={href} className="text-[#536568] hover:text-[#12343B]">{ar?ara:en}</Link>)}</nav>
  <div className="flex items-center gap-2"><button aria-label="Switch language" onClick={()=>setAr(!ar)} className="rounded-lg border border-[#d9e6e4] bg-white px-3 py-2 text-xs font-bold">{ar?"EN":"عربي"}</button><Link className="btn btn-primary text-sm" href="/book">{ar?"احجز موعدًا":"Book an Appointment"}</Link><button className="lg:hidden rounded-lg border px-3 py-2" aria-label="Open menu" onClick={()=>setOpen(!open)}>☰</button></div>
 </div>{open&&<nav className="lg:hidden container grid gap-1 pb-4">{nav.map(([href,en,ara])=><Link onClick={()=>setOpen(false)} key={href} href={href} className="rounded-lg p-3 hover:bg-white">{ar?ara:en}</Link>)}</nav>}</header>
 <main>{children}</main><footer className="bg-[#12343B] text-white"><div className="container grid gap-10 py-14 md:grid-cols-3"><div><Image src="/brand/assets/logo-dark.png" alt="Nada Smile" width={160} height={58} className="h-12 w-auto"/><p className="mt-4 max-w-sm text-sm leading-7 text-[#d5e5e3]">{ar?"رعاية أسنان عصرية بهدوء ووضوح واهتمام شخصي.":"Modern dental care with calm, clear and patient-focused communication."}</p></div><div><p className="font-semibold">{ar?"روابط سريعة":"Quick links"}</p><div className="mt-4 grid gap-2 text-sm text-[#d5e5e3]">{nav.slice(0,5).map(([href,en,ara])=><Link key={href} href={href}>{ar?ara:en}</Link>)}</div></div><div><p className="font-semibold">{ar?"تواصل":"Contact"}</p><a className="mt-4 block text-[#d5e5e3]" href="tel:+201552708582">01552708582</a><a className="block text-[#d5e5e3]" href="mailto:dr.nada2005@gmail.com">dr.nada2005@gmail.com</a></div></div><div className="container border-t border-white/10 py-5 text-xs text-[#b9ccca]">© {new Date().getFullYear()} Nada Smile Dental Clinic. All rights reserved.</div></footer></div>
}
